pribor = input("название нового прибора: ")
number = input("инвентарный номер: ")
mood = input("состояние: ")
howmany = input("количество: ")
print(f"Новый прибор\t{pribor}\nЕго инвентарный номер\t{number}\nЕго состояние\t{mood}\nВ количестве\t{howmany}")
